services:
  - type: web
    name: tourism-booking-backend
    env: node
    buildCommand: cd src && npm run install-all
    startCommand: cd src && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

  - type: static
    name: tourism-booking-frontend
    env: static
    buildCommand: cd src && npm run build
    staticPublishPath: src/frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 